feat: unstoppable domain integration
liquality/wallet-core pull request #110
Opened 2022-08-08 07:06 UTC by amritkumarj

2022-08-08 13:39 UTC, kraikov requested changes

2022-08-08 13:39 UTC, kraikov commented on package.json
> +    "@unstoppabledomains/resolution": "^8.3.1",
can you please pin the version

2022-08-08 13:43 UTC, kraikov commented on src/utils/uns.ts
> +    async lookupDomain(address: string, chainId: ChainId): Promise<string | null> {
Can you use `Nullable<string>` instead of `string | null`?

2022-08-09 08:47 UTC, monokh requested changes
Looking good!
just some small comment

2022-08-09 08:47 UTC, monokh commented on src/utils/uns.ts
> +import { HttpClient } from '@chainify/client';
`utils` seems the wrong place for this
how about `src/nameResolvers/uns.ts` ?

2022-08-09 08:47 UTC, monokh commented on src/build.config.ts
> +  resolutionService : 'https://unstoppabledomains.g.alchemy.com/domains/',
This should be grouped in some way
perhaps?
```
nameResolvers: {
  uns: {
    resolutionService: ...,
    tldAPI: ...,
    alchemyKey: ...,
  }
}
```

2022-08-10 08:31 UTC, monokh approved these changes

2022-08-10 08:48 UTC, merged