Integrate optimism
liquality/wallet-core pull request #135
Opened 2022-08-24 12:37 UTC by skeremidchiev

Optimism integration in wallet-core & cryptoassets.

2022-08-24 17:48 UTC, kraikov requested changes

2022-08-24 17:48 UTC, kraikov commented on packages/wallet-core/package.json
> +    "@eth-optimism/sdk": "^1.1.5",
pin version

2022-08-25 08:49 UTC, monokh approved these changes

2022-08-25 08:49 UTC, AndonMitev approved these changes

2022-08-25 09:53 UTC, kraikov approved these changes

2022-08-25 09:53 UTC, merged