Feat/balance batching
liquality/wallet-core pull request #64
Opened 2022-06-13 19:47 UTC by kraikov

2022-06-14 14:29 UTC, skeremidchiev approved these changes

2022-06-23 11:06 UTC, monokh requested changes

2022-06-23 11:06 UTC, monokh commented on src/store/actions/updateBalances.ts
> +      const { assets, type, chain } = account;
assets from the account are actually not the assets that was passed in to this action. It would be unexpected for those balances to update

2022-06-23 11:06 UTC, monokh commented on src/utils/arrays.ts
> +export function chunkArray<T = any>(arr: Array<T>, size: number) {
Lodash also has chunk, and we already have that in the lib, should we use that instead?

2022-06-23 11:06 UTC, monokh commented on src/store/actions/updateBalances.ts
> +      const { assets, type, chain } = account;
Maybe we should change from asset to chain?

2022-06-23 13:44 UTC, monokh commented on src/store/actions/updateBalances.ts
> +  const allEnabledAccountIds =
Why calculate all enabled if we're not going to use it (when accoundIds is provided)

2022-06-23 13:45 UTC, monokh approved these changes

2022-06-23 13:49 UTC, monokh approved these changes

2022-06-23 13:49 UTC, merged